package com.delitx.deeplapiexample.models

enum class TargetLanguage(val code: String, val languageName: String) {
    Bulgarian("BG", "Bulgarian"),
    Czech("CS", "Czech"),
    Danish("DA", "Danish"),
    German("DE", "German"),
    Greek("EL", "Greek"),
    EnglishBritish("EN-GB", "EnglishBritish"),
    EnglishAmerican("EN-US", "EnglishAmerican"),
    Spanish("ES", "Spanish"),
    Estonian("ET", "Estonian"),
    Finnish("FI", "Finnish"),
    French("FR", "French"),
    Hungarian("HU", "Hungarian"),
    Indonesian("ID", "Indonesian"),
    Italian("IT", "Italian"),
    Japanese("JA", "Japanese"),
    Korean("KO", "Korean"),
    Lithuanian("LT", "Lithuanian"),
    Latvian("LV", "Latvian"),
    Norwegian("NB", "Norwegian"),
    Dutch("NL", "Dutch"),
    Polish("PL", "Polish"),
    PortugueseBrazilian("PT-BR", "PortugueseBrazilian"),
    PortugueseEuropean("PT-PT", "PortugueseEuropean"),
    Romanian("RO", "Romanian"),
    Russian("RU", "Russian"),
    Slovak("SK", "Slovak"),
    Slovenian("SL", "Slovenian"),
    Swedish("SV", "Swedish"),
    Turkish("TR", "Turkish"),
    Ukrainian("UK", "Ukrainian"),
    Chinese("ZH", "Chinese");
}